### ISSUE TITLE
PermissionError on Windows due to TemporaryDirectory

### ISSUE THREAD

**Issue by pawamoy** [timothycrosley/cruft#13]
Running cruft on Windows (sorry about that...) I get permissions error when the temporary directory is being cleaned/removed:

```
  File "c:\users\REDACTED\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access denied: 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\1\\tmpgfoglt_v\\template\\.git\\objects\\01\\5b0e550f76098659c765b1134a830f2e5252dd'

```

There's a clue here about a bug in Python itself: https://stackoverflow.com/questions/55109076/python-tempfile-temporaryfile-hangs-on-windows-when-no-write-privilege, though the error described is not exactly the same.

Apart from using something else than `TemporaryDirectory`, I don't think cruft can do much to fix that. Just opening here in case someone else has the same issue.

Maybe using another Python version could solve the problem as well.

**Comment by pawamoy** [comment]
Actual bug is here: https://bugs.python.org/issue26660, and seems to have been fixed (but I don't know in which version). I guess I just need to upgrade my Python version.

**Comment by pawamoy** [comment]
It might actually be caused by another process using a file in the directory:

```
[WinError 32] The process cannot access the file because this file is used by another process: 'C:\\Users\\REDACTED\\AppData\\Local\\Temp\\1\\ExchangePerflog_84190844dfa6723cd6c17120.dat'
```

**Comment by chbndrhnns** [comment]
I also see this error on windows machines.

**Comment by pawamoy** [comment]
Reopening then

**Comment by timothycrosley** [comment]
This should be fixed in 1.2.0

Thanks!

~Timothy

**Comment by kiranpatel11** [comment]
I am still getting the Permission denied error with python 3.9.1 and cruft 2.6.0 !!

**Comment by sharadpattanshetti** [comment]
I am still facing this issue on my Windows10, Python 3.7 and cruft v2.8.0
Any update when the fix will be available?

**Comment by pawamoy** [comment]
We resolved this issue in Copier with this PR: https://github.com/copier-org/copier/pull/358/files
